opam-version: "2.0"
maintainer: "Cyril Cohen <cyril.cohen@inria.fr>"
version: "dev"

homepage: "https://github.com/rocq-community/coqeal"
dev-repo: "git+https://github.com/rocq-community/coqeal.git"
bug-reports: "https://github.com/rocq-community/coqeal/issues"
license: "MIT"

depends: [
  "coq-core"
  "rocq-coqeal"
]

synopsis: "Compatibility package for rocq-coqeal"
